# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='')),
                ('take', models.TextField()),
                ('pick', models.CharField(max_length=10)),
            ],
        ),
    ]
