# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draftpick', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
